/* global */
// ===== Curated content fixtures =====
// Cada item segue o cadastro: título, descrição, fonte, link, formato, tema, profundidade, data.
// "fonte" e "link" são placeholders que o usuário substituirá no Claude Code.

window.PORTAL_DATA = {
  // Single highlight that becomes the cover headline
  manchete: {
    tag: "CG-IBS · Alerta Operacional",
    titulo: "CG-IBS orienta estados a reforçarem fiscalização do ICMS até dezembro de 2026",
    porQueImporta: "A arrecadação de ICMS até 31/12/2026 serve de base para a alíquota-padrão do IBS a partir de 2029. Estados que perderem receita de ICMS fixarão uma alíquota menor de IBS — permanentemente.",
    prazo: "31 · dez · 2026",
    janela: "19 meses",
    impacto: "Alíquota IBS permanente",
    fonte: "Comitê Gestor do IBS",
    formato: "Nota técnica",
    profundidade: "Aprofundado",
    data: "23 mai 2026",
    tema: "ICMS / IBS",
  },

  // Base da Reforma — legislação, atos normativos, documentos
  base: [
    { titulo: "EC 132/2023 — Reforma Tributária do Consumo",
      descricao: "Texto-base constitucional que institui IBS, CBS e IS, define o Comitê Gestor do IBS e cria o Fundo Nacional de Desenvolvimento Regional.",
      fonte: "Congresso Nacional",
      formato: "Emenda Constitucional",
      tema: "Constitucional",
      profundidade: "Aprofundado",
      data: "20 dez 2023",
      destaque: true,
    },
    { titulo: "LC 214/2025 — Lei Geral do IBS e da CBS",
      descricao: "Regulamenta IBS e CBS: fato gerador, base de cálculo, alíquotas, regimes diferenciados, regimes específicos e split payment.",
      fonte: "Presidência da República",
      formato: "Lei Complementar",
      tema: "IBS / CBS",
      profundidade: "Aprofundado",
      data: "16 jan 2025",
      destaque: true,
    },
    { titulo: "LC 219/2025 — Comitê Gestor do IBS",
      descricao: "Institui a estrutura, governança paritária e competências do CG-IBS para administração compartilhada do tributo estadual/municipal.",
      fonte: "Presidência da República",
      formato: "Lei Complementar",
      tema: "Comitê Gestor",
      profundidade: "Aprofundado",
      data: "04 mar 2025",
    },
    { titulo: "PLP 108/2024 — Processo administrativo e contencioso",
      descricao: "Em tramitação. Define o processo administrativo do IBS, contencioso e sistema de distribuição entre entes.",
      fonte: "Câmara dos Federados",
      formato: "Projeto de Lei",
      tema: "Contencioso",
      profundidade: "Aprofundado",
      data: "Em tramitação",
      situacao: "Em análise no Senado",
    },
    { titulo: "Resolução CG-IBS nº 07/2026 — Esforço de arrecadação",
      descricao: "Orienta administrações tributárias estaduais a sustentar arrecadação de ICMS até 2026, base de cálculo da alíquota futura do IBS.",
      fonte: "Comitê Gestor do IBS",
      formato: "Resolução",
      tema: "Transição",
      profundidade: "Intermediário",
      data: "10 mai 2026",
      novidade: true,
    },
    { titulo: "Decreto Estadual nº 5.842-R/2026 — Comitê estadual de transição",
      descricao: "Cria, no âmbito do Governo do Estado do Espírito Santo, comitê interinstitucional para acompanhar a implementação da Reforma Tributária.",
      fonte: "Governo do Estado do ES",
      formato: "Decreto Estadual",
      tema: "Governança ES",
      profundidade: "Introdutório",
      data: "19 mai 2026",
      novidade: true,
    },
  ],

  // Estudos e Capacitação — vídeos, palestras, artigos, apresentações
  estudos: [
    { titulo: "Bernard Appy responde — IBS, alíquota de referência e impactos federativos",
      descricao: "Conversa com o secretário extraordinário da Reforma Tributária sobre regulamentação, transição e papel dos estados.",
      fonte: "Tesouro Nacional / TV NBR",
      formato: "Vídeo",
      duracao: "1h 12min",
      tema: "Visão Geral",
      profundidade: "Introdutório",
      data: "16 mai 2026",
      destaque: true,
    },
    { titulo: "O efeito da Reforma sobre a arrecadação dos estados — modelo econométrico",
      descricao: "Estudo do IPEA estima ganhos e perdas estaduais entre 2027 e 2033 sob diferentes hipóteses de alíquota de referência.",
      fonte: "IPEA",
      formato: "Artigo técnico",
      paginas: "48 págs",
      tema: "Impacto fiscal",
      profundidade: "Especialista",
      data: "08 mai 2026",
    },
    { titulo: "Setor atacadista capixaba e a Reforma — workshop SEFAZ-ES",
      descricao: "Apresentação do estudo encomendado pela SEFAZ que projeta perda potencial de R$ 9,8 bi para o setor atacadista do ES até 2033.",
      fonte: "SEFAZ-ES · Subsecretaria de Estudos Econômicos",
      formato: "Apresentação",
      paginas: "62 slides",
      tema: "Impacto ES",
      profundidade: "Aprofundado",
      data: "29 abr 2026",
      destaque: true,
    },
    { titulo: "Split payment na prática — como funcionará para o varejo",
      descricao: "Webinar do IBET destrincha o mecanismo de split payment, calendário de adoção e adequações nos sistemas de meios de pagamento.",
      fonte: "IBET",
      formato: "Vídeo",
      duracao: "58min",
      tema: "Operacional",
      profundidade: "Intermediário",
      data: "22 abr 2026",
    },
    { titulo: "Federalismo fiscal pós-Reforma — quem ganha, quem perde",
      descricao: "Nota técnica do CEFE/FGV sobre a redistribuição de receitas entre entes federados no novo modelo.",
      fonte: "FGV · CEFE",
      formato: "Nota técnica",
      paginas: "24 págs",
      tema: "Federalismo",
      profundidade: "Aprofundado",
      data: "15 abr 2026",
    },
    { titulo: "Curso EAD — Fundamentos do IBS e da CBS",
      descricao: "Trilha de capacitação em 6 módulos do Comitê Gestor para servidores estaduais e municipais. Certificação ao final.",
      fonte: "CG-IBS · Escola Virtual",
      formato: "Curso",
      duracao: "16h",
      tema: "Capacitação",
      profundidade: "Introdutório",
      data: "Permanente",
    },
  ],

  // Radar Tesouro — notícias, atualizações
  radar: [
    { kicker: "Comitê Gestor", title: "CG-IBS define cronograma de homologação dos sistemas estaduais para o piloto de 2027", date: "22 mai 2026", fonte: "Valor Econômico" },
    { kicker: "ES · Impacto", title: "Atacadistas capixabas projetam perda de R$ 9,8 bi com a Reforma até 2033",       date: "20 mai 2026", fonte: "A Gazeta" },
    { kicker: "Governança ES", title: "Governador instala comitê estadual de acompanhamento da Reforma Tributária",   date: "19 mai 2026", fonte: "Agência ES" },
    { kicker: "Transição",    title: "Receita Federal libera primeira versão do leiaute técnico da CBS para testes",  date: "17 mai 2026", fonte: "RFB" },
    { kicker: "Federalismo",  title: "FNDR pode ter critérios revistos em PLP que tramita no Senado",                  date: "15 mai 2026", fonte: "Folha de S.Paulo" },
    { kicker: "Capacitação",  title: "Tesouro Nacional abre inscrições para curso de avaliação de impacto fiscal",     date: "14 mai 2026", fonte: "STN" },
  ],

  // Ciclo de palestras — agenda viva
  ciclo: {
    titulo: "Ciclo de Palestras Tesouro Estadual",
    edicao: "5ª edição · maio – julho 2026",
    proximo: {
      n: "07",
      data: { dia: "11", mes: "jun", ano: "2026", hora: "14h às 17h" },
      titulo: "Alíquota de referência do IBS: como ela é calculada e por que importa para os estados",
      palestrante: "Bernard Appy",
      cargo: "Secretário Extraordinário da Reforma Tributária · MF",
      local: "Auditório do Palácio da Fonte Grande · Vitória",
      modalidade: "Presencial + transmissão ao vivo",
    },
    proximos: [
      { n: "08", data: "25 jun · qui · 14h", titulo: "Split payment e seu efeito sobre o fluxo de caixa do Estado", palestrante: "Vanessa Canado · MF" },
      { n: "09", data: "09 jul · qua · 14h", titulo: "Contencioso do IBS: como ficam os créditos do contribuinte capixaba", palestrante: "Hamilton Dias de Souza" },
      { n: "10", data: "23 jul · qua · 14h", titulo: "Memória técnica da Reforma — Tesouro ES presta contas",       palestrante: "Equipe Tesouro Estadual" },
    ],
  },

  // Sobre / curadoria
  curadoria: {
    pilares: [
      "Fontes oficiais e reconhecidas no debate fiscal brasileiro.",
      "Pertinência clara para a operação do Tesouro Estadual capixaba.",
      "Catalogação consistente: formato, tema, profundidade e data sempre presentes.",
      "Inclusão manual — nada de feed automático; cada item passa por curadoria.",
    ],
    equipe: "Subsecretaria de Estudos e Acompanhamento Fiscal — SEAF · SEFAZ-ES",
    contato: "radar.tesouro@sefaz.es.gov.br",
    cadencia: "Atualização semanal aos sextas-feiras; alertas operacionais conforme necessidade.",
  },

  // Total counts shown on the index strip
  totais: {
    base: 24,
    estudos: 38,
    radar: 142,
    palestras: 6,
  },
};
